<template>
  <div class="container py-12 mx-auto">
    <h2>Select a calculator below</h2>
    <div class="options-container mx-auto">
      <div class="option">
        <router-link to="/mortgage-calculator">
          <img src="../../../resources/icons/Calculator.svg">
        </router-link>
        <p>Mortgage Calculator</p>
      </div>
      <div class="option">
        <a href="#">
          <img src="../../../resources/icons/Search.svg">
        </a>
        <p>How much can I afford?</p>
      </div>
      <div class="option">
        <a href="#">
          <img src="../../../resources/icons/Move.svg">
        </a>
        <p>Should I rent or by a home?</p>
      </div>
      <div class="option">
        <a href="#">
          <img src="../../../resources/icons/Refi.svg">
        </a>
        <p>Should I refinance my mortgage?</p>
      </div>
      <div class="option">
        <a href="#">
          <img src="../../../resources/icons/Report.svg">
        </a>
        <p>Comparing mortgage terms</p>
      </div>
      <div class="option">
        <a href="#">
          <img src="../../../resources/icons/Percent.svg">
        </a>
        <p>Should I pay discount points for a lower interest rates?</p>
      </div>
      <div class="option">
        <a href="#">
          <img src="../../../resources/icons/Star.svg">
        </a>
        <p>Compare a 'no-cost' vs traditional mortgage</p>
      </div>
      <div class="option">
        <a href="#">
          <img src="../../../resources/icons/Bank.svg">
        </a>
        <p>What are the tax savings generated by my mortgage?</p>
      </div>
      <div class="option">
        <a href="#">
          <img src="../../../resources/icons/Chart.svg">
        </a>
        <p>Adjustable rate mortgage calculator</p>
      </div>
      <div class="option">
        <a href="#">
          <img src="../../../resources/icons/Checklist.svg">
        </a>
        <p>Loan comparison calculator</p>
      </div>
    </div>
  </div>
</template>

<style>
    .options-container{
        width: 75%;
        display: flex;
        flex-wrap: wrap;
        justify-content: space-around;
        align-items: flex-start;
    }

    .options-container .option{
        width: 16%;
        margin: 0.9rem;
        text-align: center;
        display: flex;
        flex-direction: column;
        justify-content: space-between;
        align-items: center;
    }
    .option img{
        max-height: 60px;
        justify-self: start;
    }
</style>

<script>
  export default {
    //
  }
</script>
